export const GET_NAMES = "GET_NAMES";
export const GET_NAMES_SUCCESS = "GET_NAMES_SUCCESS";
export const GET_NAMES_ERROR = "GET_NAMES_ERROR";

export const GET_TRENDING_NAMES = "GET_TRENDING_NAMES";
export const GET_TRENDING_NAMES_SUCCESS = "GET_TRENDING_NAMES_SUCCESS";
export const GET_TRENDING_NAMES_ERROR = "GET_TRENDING_NAMES_ERROR";

export const SET_GENDER = "SET_GENDER";
export const CLEAR_GENDER = "CLEAR_GENDER";

export const SET_RELIGION = "SET_RELIGION";
export const CLEAR_RELIGION = "CLEAR_RELIGION";

export const SET_KEYWORD = "SET_KEYWORD";
export const CLEAR_KEYWORD = "CLEAR_KEYWORD";
